### ISSUE TITLE
Relations not working correctly?

### ISSUE THREAD

**Issue by ecamaj** [sirensolutions/kibi#32]
Hi,

i noticed some strange behaviors (or I’m doing something wrong, of course) where relations are behaving very strangely. 

Short explanation - when filtering accounts based on all transactions, I get listed some accounts that are not connected with transactions as a Payee (“platitelj_racun”).

Screencast link: https://www.dropbox.com/s/q9qjuc7d2qu97a5/Kibi%20screencast.mp4?dl=0

Explained:
- in screencast you can see definition: transactions.platitelj_racun -> accounts.iban
- in transactions dashboard click on relation to accounts based on relation above
- showing accounts (that should be) connected to transactions
- filtering one of those account in accounts tab
- returning to transactions tab and filtering same there
- nothing returned - where there should be at least one transaction with “platitelj_racun” having that account

Kibi version: 4.4.1, Build  9010
Sire plugin version: 2.2.0-1
ES version: 2.2.0

If any more information is needed, just ask.

**Comment by scampi** [comment]
Can you check the query of the filter added by the click on the button (click on the edit icon next to bin one) and see if there is a `termsEncoding` appearing there on the same level as `indices`. There should be two.
If not, please add the following `"termsEncoding": "long"` to both objects.

If that solves your problem, this is indeed a bug and we'll make a new release.

**Comment by ecamaj** [comment]
Still not working unfortunately.
More details in the document attached.

[Kibi relational filter not working.docx](https://github.com/sirensolutions/kibi/files/281565/Kibi.relational.filter.not.working.docx)

Thanks, 
Eddie

**Comment by scampi** [comment]
Thanks @ecamaj for the doc.
- what is the mapping for the fields `transactions.iban_primatelja` and `account_owner.iban` ?
- regarding the confusing message `... related to (1) from ....`, I am currently fixing that.
- regarding the error `Kibi Relational filter: "SearchPhaseExecutionException[all shards failed]; nested: QueryParsingException[[fielddata_terms] field 'iban' does not exist in index 'transactions-2016.05.24'.]; "` please open a separate issue with possibly some more information to reproduce it. We had in the past similar errors that we corrected, but it is possible some case was overlooked.

**Comment by scampi** [comment]
There is a new release https://github.com/sirensolutions/kibi/releases/tag/tag-4.4.1-1 with some fixes.
Could you try that one ?

**Comment by ecamaj** [comment]
Still not good.
Document attached.
[kibi-problems2.docx](https://github.com/sirensolutions/kibi/files/285915/kibi-problems2.docx)

**Comment by ecamaj** [comment]
And answers to your question...

**what is the mapping for the fields transactions.iban_primatelja and account_owner.iban ?**

transactions.iban_primatelja: {
        "index": "not_analyzed",
        "type": "string"
      }

accounts_owner.iban: {
        "type": "string"
      }

**Comment by scampi** [comment]
You should have the same mapping on the fields you are joining on.
Since iban is analyzed, you have "hr6423400091987654321" joining with "HR6423400091987654321" (notice the lowercase).

**Comment by ecamaj** [comment]
Huh... this is strange. Where can I see this lowered case version? Since in Kibana/Kibi, JSON format of data for a document in Accounts says:

 "iban": "HR6423400091987654321"

tnx

**Comment by scampi** [comment]
Can you try these two commands and show me their output ?

``` sh
$ curl -XGET 'localhost:9220/transactions/_analyze' -d '
{
  "field" : "iban_primatelja",
  "text": "HR6423400091987654321"
}'
```

``` sh
$ curl -XGET 'localhost:9220/accounts_owner/_analyze' -d '
{
  "field" : "iban",
  "text": "HR6423400091987654321"
}'
```

**Comment by ecamaj** [comment]
Yes, you are right, with the same mapping, it is working.
Is there way to mitigate such problems? Seems to me that Kibi should be aware of this possibility and map fields regardless of "not_analyzed" property. (Any other?)

Thank you for your support.

**Comment by scampi** [comment]
No problem @ecamaj .
There is no way to mitigate this problem, joined fields must have identical mapping definitions. We'll try to add a check in kibi to notify the user about this, so that he may correct the field definition.
