### ISSUE TITLE
4 verbose stack Error: missing script: uiFramework:build

### ISSUE THREAD

**Issue by xycloud** [sirensolutions/kibi#95]
version: kibi: 5.4.0-beta-2
command: npm run uiFramework:build
error: npm ERR! missing script: uiFramework:build

**Comment by szydan** [comment]
Hi @xycloud 
Could you try if this happens also on master, please 
Note that we released 5.4.3-3 
Which can be downloaded from our portal at 
https://support.siren.io/support/solutions/articles/17000062219-platform-5-4-3-3

**Comment by xycloud** [comment]
still ```missing script: uiFramework:build``` in 5.4.3-3, but master is ok

**Comment by szydan** [comment]
@xycloud you have to register to view the URL (it is completely free to register and then you can download and 2 kinds of free licenses. 
unlimited version for 30 days, or 
limited version for 1 user 1 node)
Here a link to get the license once you register 
https://support.siren.io/support/solutions/articles/17000057493-get-your-license

**Comment by xycloud** [comment]
hi szydan:

i download the 5.4.3-3, but still missing script: uiFramework:build in 5.4.3-3.
however kibi master is ok

**Comment by szydan** [comment]
@xycloud Big Thanks for trying all these versions 
Do you need the script in 5.4.3 or you are fine using master 
Just to let you know current master is based on Kibana 5.5.2 but will soon be moved to Kibana 5.6.3

**Comment by xycloud** [comment]
hi szydan:

i still need the 5.4.3, would you please add this script to 5.4.3?

thanks very much!!

**Comment by xycloud** [comment]
so strange
